//! Compile-time reflection infrastructure.
//!
//! The `Reflect` trait is auto-derived by `#[derive(Reflect)]` from `quasar-derive`.
//! It provides:
//! - Field descriptors with metadata (type name, range constraints)
//! - JSON serialization / deserialization
//! - Network binary serialization / deserialization

/// Metadata for a single field in a reflected struct.
pub struct FieldDescriptor {
    /// The field name (e.g. `"x"`, `"health"`).
    pub name: &'static str,
    /// The Rust type name (e.g. `"f32"`, `"bool"`).
    pub type_name: &'static str,
    /// Optional numeric range constraint `(min, max)` from `#[reflect(range = "...")]`.
    pub range: Option<(f64, f64)>,
}

/// Compile-time reflection trait, auto-generated by `#[derive(Reflect)]`.
pub trait Reflect: Sized {
    /// Returns the struct type name.
    fn type_name(&self) -> &'static str;

    /// Static field descriptors for schema generation.
    fn field_descriptors() -> &'static [FieldDescriptor];

    /// Serialize to a JSON value.
    fn to_json(&self) -> serde_json::Value;

    /// Deserialize from a JSON value.
    fn from_json(value: &serde_json::Value) -> Option<Self>;

    /// Serialize to compact binary for network transport (little-endian).
    fn net_serialize(&self) -> Vec<u8>;

    /// Deserialize from compact binary.
    fn net_deserialize(data: &[u8]) -> Option<Self>;
}
