//! Core renderer — manages the wgpu device, surface, and draw calls.

use quasar_core::error::{QuasarError, QuasarResult};

use super::camera::{Camera, CameraUniform};
use super::light::LightsUniform;
use super::material::{Material, MaterialOverride};
use super::mesh::Mesh;
use super::occlusion::{DrawIndexedIndirectArgs, GpuCullPass, IndirectDrawManager, MeshDrawCommand};
use super::pipeline;
use super::taa::TaaPass;
use super::ssgi::SsgiPass;
use super::texture::Texture;

/// Maximum number of objects that can be rendered in a single pass with
/// unique model matrices.
const MAX_RENDER_OBJECTS: usize = 4096;

/// Rendering configuration options.
#[derive(Debug, Clone, Copy)]
pub struct RenderConfig {
    /// MSAA sample count (1 = no MSAA, 4 = 4x MSAA).
    pub msaa_sample_count: u32,
    /// Enable GPU-driven culling via compute shader + indirect draws.
    pub gpu_driven_culling: bool,
    /// Enable Temporal Anti-Aliasing (TAA).
    pub taa_enabled: bool,
    /// Enable Screen-Space Global Illumination (SSGI).
    pub ssgi_enabled: bool,
}

impl Default for RenderConfig {
fn default() -> Self {
// Desktop defaults: enable advanced features
#[cfg(not(target_arch = "wasm32"))]
{
Self {
msaa_sample_count: 1,
gpu_driven_culling: true,
taa_enabled: true,
ssgi_enabled: true,
}
}
// Web/WASM defaults: disable GPU-heavy features
#[cfg(target_arch = "wasm32")]
{
Self {
msaa_sample_count: 1,
gpu_driven_culling: false,
taa_enabled: false,
ssgi_enabled: false,
}
}
}
}

/// The main GPU renderer for Quasar Engine.
///
/// Owns the wgpu device, queue, surface, and render pipeline. Provides a
/// high-level `draw` method that submits meshes for rendering each frame.
pub struct Renderer {
    pub device: wgpu::Device,
    pub queue: wgpu::Queue,
    pub surface: wgpu::Surface<'static>,
    pub config: wgpu::SurfaceConfiguration,
    pub render_config: RenderConfig,
    pub render_pipeline: wgpu::RenderPipeline,
    pub depth_texture: wgpu::Texture,
    pub depth_view: wgpu::TextureView,
    pub camera_buffer: wgpu::Buffer,
    pub camera_bind_group: wgpu::BindGroup,
    pub camera_bind_group_layout: wgpu::BindGroupLayout,
    pub camera_uniform: CameraUniform,
    pub material_texture_bind_group_layout: wgpu::BindGroupLayout,
    pub light_buffer: wgpu::Buffer,
    pub lighting_bind_group: wgpu::BindGroup,
    pub lighting_bind_group_layout: wgpu::BindGroupLayout,
    pub light_uniform: LightsUniform,
    /// Default white material used when no material is specified.
    pub default_material: Material,
    /// Default 1×1 white texture used when no texture is specified.
    pub default_texture: Texture,
    /// Combined bind group for default material + texture.
    pub default_material_texture_bind_group: wgpu::BindGroup,
    /// Textures that can be used by entities.
    pub textures: Vec<Texture>,
    /// Material + texture bind groups for quick access.
    pub material_texture_bind_groups: Vec<wgpu::BindGroup>,
    /// Minimum uniform buffer offset alignment (bytes), from device limits.
    pub uniform_alignment: u32,
    /// Instance data buffer for GPU instancing (model matrices).
    pub instance_buffer: wgpu::Buffer,
    /// Bind group for instance data (storage buffer with model matrices).
    pub instance_bind_group: wgpu::BindGroup,
    /// Bind group layout for instance data.
    pub instance_bind_group_layout: wgpu::BindGroupLayout,
    /// GPU compute-based frustum/occlusion culling pass (when enabled).
    pub gpu_cull_pass: Option<GpuCullPass>,
    /// Indirect draw command manager for GPU-driven rendering.
    pub indirect_draw_manager: Option<IndirectDrawManager>,
    /// TAA pass — temporal anti-aliasing with jittered projection.
    pub taa_pass: Option<TaaPass>,
    /// Zero-filled motion vector texture (Rg16Float) used as placeholder
    /// until a proper velocity buffer is generated by the geometry pass.
    pub motion_vector_texture: Option<wgpu::Texture>,
    pub motion_vector_view: Option<wgpu::TextureView>,
    /// SSGI pass — screen-space global illumination compute.
    pub ssgi_pass: Option<SsgiPass>,
}

impl Renderer {
    /// Initialize the renderer for a given window.
    ///
    /// This creates the wgpu instance, adapter, device, surface, pipeline, and
    /// depth buffer — everything needed to start drawing.
    pub async fn new(
        window: std::sync::Arc<winit::window::Window>,
        width: u32,
        height: u32,
        render_config: RenderConfig,
    ) -> QuasarResult<Self> {
        // Create wgpu instance with default backends.
        let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
            backends: wgpu::Backends::all(),
            ..Default::default()
        });

        // Create the rendering surface from the window.
        let surface = instance
            .create_surface(window.clone())
            .map_err(|e| QuasarError::Render(format!("Failed to create surface: {e}")))?;

        // Request a GPU adapter compatible with our surface.
        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                compatible_surface: Some(&surface),
                force_fallback_adapter: false,
            })
            .await
            .ok_or_else(|| QuasarError::Render("No suitable GPU adapter found".into()))?;

        log::info!("GPU adapter: {:?}", adapter.get_info().name);

        // Request the device and queue.
        let mut required_features = wgpu::Features::empty();
        if render_config.gpu_driven_culling {
            required_features |= wgpu::Features::MULTI_DRAW_INDIRECT;
        }
        let (device, queue) = adapter
            .request_device(
                &wgpu::DeviceDescriptor {
                    label: Some("Quasar Device"),
                    required_features,
                    required_limits: wgpu::Limits::default(),
                    memory_hints: Default::default(),
                },
                None,
            )
            .await
            .map_err(|e| QuasarError::Render(format!("Failed to request device: {e}")))?;

        // Configure the surface.
        let surface_caps = surface.get_capabilities(&adapter);
        let format = surface_caps
            .formats
            .iter()
            .find(|f| f.is_srgb())
            .copied()
            .unwrap_or(surface_caps.formats[0]);

        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format,
            width,
            height,
            present_mode: wgpu::PresentMode::AutoVsync,
            alpha_mode: surface_caps.alpha_modes[0],
            view_formats: vec![],
            desired_maximum_frame_latency: 2,
        };
        surface.configure(&device, &config);

        // -- Camera uniform buffer + bind group (dynamic offsets) --
        let camera_uniform = CameraUniform::new();
        let uniform_alignment = device.limits().min_uniform_buffer_offset_alignment;
        let uniform_size = std::mem::size_of::<CameraUniform>() as u32;
        let aligned_size = uniform_size.div_ceil(uniform_alignment) * uniform_alignment;
        let camera_buffer_size = aligned_size as u64 * MAX_RENDER_OBJECTS as u64;

        let camera_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Camera Uniform Buffer"),
            size: camera_buffer_size,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let camera_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Camera Bind Group Layout"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: true,
                        min_binding_size: std::num::NonZeroU64::new(uniform_size as u64),
                    },
                    count: None,
                }],
            });

        let camera_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Camera Bind Group"),
            layout: &camera_bind_group_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                    buffer: &camera_buffer,
                    offset: 0,
                    size: std::num::NonZeroU64::new(uniform_size as u64),
                }),
            }],
        });

        // -- Depth texture --
        let (depth_texture, depth_view) = Self::create_depth_texture(&device, width, height, render_config.msaa_sample_count);

        // -- Create merged material + texture bind group layout --
        let material_texture_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Material + Texture Bind Group Layout"),
                entries: &[
                    // Material uniform (binding 0)
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    // Albedo texture (binding 1)
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            multisampled: false,
                            view_dimension: wgpu::TextureViewDimension::D2,
                            sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        },
                        count: None,
                    },
                    // Albedo sampler (binding 2)
                    wgpu::BindGroupLayoutEntry {
                        binding: 2,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                        count: None,
                    },
                ],
            });

        // -- Create lighting (light + shadow) bind group layout --
        let lighting_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Lighting Bind Group Layout"),
                entries: &[
                    // Lights storage (binding 0)
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    // Shadow uniform (binding 1)
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    // Shadow map texture (binding 2)
                    wgpu::BindGroupLayoutEntry {
                        binding: 2,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            multisampled: false,
                            view_dimension: wgpu::TextureViewDimension::D2,
                            sample_type: wgpu::TextureSampleType::Depth,
                        },
                        count: None,
                    },
                    // Shadow comparison sampler (binding 3)
                    wgpu::BindGroupLayoutEntry {
                        binding: 3,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Comparison),
                        count: None,
                    },
                    // Shadow depth sampler (binding 4)
                    wgpu::BindGroupLayoutEntry {
                        binding: 4,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                        count: None,
                    },
                    // CSM cascades storage (binding 5)
                    wgpu::BindGroupLayoutEntry {
                        binding: 5,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    // CSM cascade shadow texture array (binding 6)
                    wgpu::BindGroupLayoutEntry {
                        binding: 6,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            multisampled: false,
                            view_dimension: wgpu::TextureViewDimension::D2Array,
                            sample_type: wgpu::TextureSampleType::Depth,
                        },
                        count: None,
                    },
                ],
            });

        // -- Light storage buffer --
        let light_uniform = LightsUniform::default();
        let light_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Light Buffer"),
            size: std::mem::size_of::<LightsUniform>() as u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        
        // -- Create dummy shadow resources for bindings 1-6 --
        // Shadow uniform buffer (binding 1)
        let shadow_uniform_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Dummy Shadow Uniform Buffer"),
            size: 64, // mat4x4<f32> + vec4<f32>
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        // Dummy depth texture for shadow map (binding 2)
        let shadow_texture = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("Dummy Shadow Texture"),
            size: wgpu::Extent3d {
                width: 1,
                height: 1,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Depth32Float,
            usage: wgpu::TextureUsages::TEXTURE_BINDING,
            view_formats: &[],
        });
        let shadow_view = shadow_texture.create_view(&wgpu::TextureViewDescriptor::default());

        // Shadow comparison sampler (binding 3)
        let shadow_sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("Dummy Shadow Sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::FilterMode::Nearest,
            compare: Some(wgpu::CompareFunction::LessEqual),
            ..Default::default()
        });

        // Shadow depth sampler (binding 4)
        let shadow_depth_sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("Dummy Shadow Depth Sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Nearest,
            min_filter: wgpu::FilterMode::Nearest,
            mipmap_filter: wgpu::FilterMode::Nearest,
            ..Default::default()
        });

        // CSM cascades storage buffer (binding 5)
        let csm_cascades_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Dummy CSM Cascades Buffer"),
            size: 256, // 4 * CascadeUniform (64 bytes each)
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        // Dummy CSM cascade shadow texture array (binding 6)
        let csm_shadow_texture = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("Dummy CSM Shadow Texture Array"),
            size: wgpu::Extent3d {
                width: 1,
                height: 1,
                depth_or_array_layers: 4, // CASCADE_COUNT
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Depth32Float,
            usage: wgpu::TextureUsages::TEXTURE_BINDING,
            view_formats: &[],
        });
        let csm_shadow_view = csm_shadow_texture.create_view(&wgpu::TextureViewDescriptor {
            dimension: Some(wgpu::TextureViewDimension::D2Array),
            ..Default::default()
        });

        // -- Lighting bind group (merged light + shadow) --
        let lighting_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Lighting Bind Group"),
            layout: &lighting_bind_group_layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                        buffer: &light_buffer,
                        offset: 0,
                        size: None,
                    }),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                        buffer: &shadow_uniform_buffer,
                        offset: 0,
                        size: None,
                    }),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::TextureView(&shadow_view),
                },
                wgpu::BindGroupEntry {
                    binding: 3,
                    resource: wgpu::BindingResource::Sampler(&shadow_sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 4,
                    resource: wgpu::BindingResource::Sampler(&shadow_depth_sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 5,
                    resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                        buffer: &csm_cascades_buffer,
                        offset: 0,
                        size: None,
                    }),
                },
                wgpu::BindGroupEntry {
                    binding: 6,
                    resource: wgpu::BindingResource::TextureView(&csm_shadow_view),
                },
            ],
        });

        // -- Default material (white, roughness=0.5, metallic=0) --
        let default_material =
            Material::new(&device, &material_texture_bind_group_layout, "Default");

    // -- Default 1×1 white texture --
    let default_texture =
        Texture::white(&device, &queue, &material_texture_bind_group_layout);

        // -- Instance buffer for GPU instancing --
        let max_instances = MAX_RENDER_OBJECTS;
        let matrix_size = std::mem::size_of::<glam::Mat4>() as u64;
        let instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Instance Buffer"),
            size: matrix_size * max_instances as u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

    // Note: Instance data is currently not used in the basic shader.
    // This bind group layout is reserved for future GPU-driven rendering features.
    let instance_bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("Instance Bind Group Layout"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        });

        let instance_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Instance Bind Group"),
            layout: &instance_bind_group_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                    buffer: &instance_buffer,
                    offset: 0,
                    size: None,
                }),
            }],
        });

        // -- Create merged material + texture bind group layout --
        let material_texture_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Material + Texture Bind Group Layout"),
                entries: &[
                    // Material uniform (binding 0)
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    // Albedo texture (binding 1)
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            multisampled: false,
                            view_dimension: wgpu::TextureViewDimension::D2,
                            sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        },
                        count: None,
                    },
                    // Albedo sampler (binding 2)
                    wgpu::BindGroupLayoutEntry {
                        binding: 2,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                        count: None,
                    },
                ],
            });

        // -- Render pipeline --
        let shader_source = include_str!("../../../assets/shaders/basic.wgsl");
        let render_pipeline = pipeline::create_render_pipeline(
            &device,
            format,
            &camera_bind_group_layout,
            &material_texture_bind_group_layout,
            &lighting_bind_group_layout,
            shader_source,
        );

        // Upload default material data.
        default_material.update(&queue);

        // Upload light data.
        queue.write_buffer(&light_buffer, 0, bytemuck::cast_slice(&[light_uniform]));

        // Create combined material + texture bind group for default material and texture
        let default_material_texture_bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Default Material + Texture Bind Group"),
            layout: &material_texture_bind_group_layout,
            entries: &[
                // Material uniform (binding 0)
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                        buffer: &default_material.buffer,
                        offset: 0,
                        size: None,
                    }),
                },
                // Albedo texture (binding 1)
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::TextureView(&default_texture.view),
                },
                // Albedo sampler (binding 2)
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Sampler(&default_texture.sampler),
                },
            ],
        });

        let mut result = Ok(Self {
            device,
            queue,
            surface,
            config,
            render_config,
            render_pipeline,
            depth_texture,
            depth_view,
            camera_buffer,
            camera_bind_group,
            camera_bind_group_layout,
            camera_uniform,
            material_texture_bind_group_layout,
            light_buffer,
            lighting_bind_group,
            lighting_bind_group_layout,
            light_uniform,
            default_material,
            default_texture,
            default_material_texture_bind_group,
            textures: Vec::new(),
            material_texture_bind_groups: Vec::new(),
            uniform_alignment,
            instance_buffer,
            instance_bind_group,
            instance_bind_group_layout,
            gpu_cull_pass: None,
            indirect_draw_manager: None,
            taa_pass: None,
            motion_vector_texture: None,
            motion_vector_view: None,
            ssgi_pass: None,
        });
        if let Ok(ref mut renderer) = result {
            if renderer.render_config.gpu_driven_culling {
                renderer.gpu_cull_pass = Some(GpuCullPass::new(&renderer.device));
                renderer.indirect_draw_manager = Some(IndirectDrawManager::new());
            }
            if renderer.render_config.taa_enabled {
                let w = renderer.config.width;
                let h = renderer.config.height;
                renderer.taa_pass = Some(TaaPass::new(
                    &renderer.device,
                    w,
                    h,
                    renderer.config.format,
                ));
                let (mv_tex, mv_view) = Self::create_motion_vector_texture(&renderer.device, w, h);
                renderer.motion_vector_texture = Some(mv_tex);
                renderer.motion_vector_view = Some(mv_view);
            }
            if renderer.render_config.ssgi_enabled {
                let w = renderer.config.width;
                let h = renderer.config.height;
                renderer.ssgi_pass = Some(SsgiPass::new(&renderer.device, w, h));
            }
        }
        result
    }

    /// Handle window resize — reconfigure surface and depth buffer.
    pub fn resize(&mut self, width: u32, height: u32) {
        if width == 0 || height == 0 {
            return;
        }
        self.config.width = width;
        self.config.height = height;
        self.surface.configure(&self.device, &self.config);

        let (depth_texture, depth_view) = Self::create_depth_texture(&self.device, width, height, self.render_config.msaa_sample_count);
        self.depth_texture = depth_texture;
        self.depth_view = depth_view;

        if let Some(taa) = self.taa_pass.as_mut() {
            taa.resize(&self.device, width, height);
            let (mv_tex, mv_view) = Self::create_motion_vector_texture(&self.device, width, height);
            self.motion_vector_texture = Some(mv_tex);
            self.motion_vector_view = Some(mv_view);
        }
        if let Some(ssgi) = self.ssgi_pass.as_mut() {
            ssgi.resize(&self.device, width, height);
        }
    }

    /// Upload instance transform matrices to the GPU instance buffer.
    ///
    /// Called by the runner after ECS systems have collected the matrices
    /// into [`RenderSyncOutput`].
    pub fn upload_instance_transforms(&self, transforms: &[glam::Mat4]) {
        if transforms.is_empty() {
            return;
        }
        let bytes = bytemuck::cast_slice(transforms);
        let max = self.instance_buffer.size() as usize;
        let len = bytes.len().min(max);
        self.queue
            .write_buffer(&self.instance_buffer, 0, &bytes[..len]);
    }

    /// Update the camera uniform buffer on the GPU.
    pub fn update_camera(&mut self, camera: &Camera, model: glam::Mat4) {
        self.camera_uniform.update(camera, model);
        self.queue.write_buffer(
            &self.camera_buffer,
            0,
            bytemuck::cast_slice(&[self.camera_uniform]),
        );
    }

    /// Add a texture to the renderer and return its index.
    ///
    /// The returned index can be used with `TextureHandle` to specify which
    /// texture an entity should use.
    pub fn add_texture(&mut self, texture: Texture) -> u32 {
        let index = self.textures.len() as u32;
        self.textures.push(texture);
        index
    }

    /// Create a combined material + texture bind group for a given material and texture.
    ///
    /// The shader expects material uniform (binding 0), texture (binding 1), and sampler (binding 2)
    /// all in the same bind group (group 1).
    pub fn create_material_texture_bind_group(
        &self,
        material: &Material,
        texture: &Texture,
    ) -> wgpu::BindGroup {
        self.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Material + Texture Bind Group"),
            layout: &self.material_texture_bind_group_layout,
            entries: &[
                // Material uniform (binding 0)
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                        buffer: &material.buffer,
                        offset: 0,
                        size: None,
                    }),
                },
                // Albedo texture (binding 1)
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::TextureView(&texture.view),
                },
                // Albedo sampler (binding 2)
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Sampler(&texture.sampler),
                },
            ],
        })
    }

    /// Add a texture from a file path.
    pub fn add_texture_from_file(&mut self, path: impl AsRef<std::path::Path>) -> Result<u32, String> {
        let texture = Texture::from_file(
            &self.device,
            &self.queue,
            &self.material_texture_bind_group_layout,
            path,
        )?;
        Ok(self.add_texture(texture))
    }

    /// Get a texture bind group by index.
    ///
    /// Returns the default texture if the index is out of bounds.
    pub fn get_texture_bind_group(&self, index: u32) -> &wgpu::BindGroup {
        if index == 0 || index as usize > self.material_texture_bind_groups.len() {
            &self.default_texture.bind_group
        } else {
            &self.material_texture_bind_groups[index as usize - 1]
        }
    }

    // ── Split-phase rendering API ────────────────────────────────

    /// Acquire the next surface frame and create a fresh command encoder.
    ///
    /// Use together with [`render_3d_pass`](Self::render_3d_pass) and
    /// [`finish_frame`](Self::finish_frame) when you need to inject
    /// additional render passes (e.g. egui) between the 3D draw and
    /// presentation.
    pub fn begin_frame(
        &self,
    ) -> Result<(wgpu::SurfaceTexture, wgpu::TextureView, wgpu::CommandEncoder), wgpu::SurfaceError>
    {
        let output = self.surface.get_current_texture()?;
        let view = output
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());
        let encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("Render Encoder"),
            });
        Ok((output, view, encoder))
    }

    /// Perform the 3D clear + draw pass using an externally-owned encoder.
    ///
    /// All per-object camera uniforms are written to the GPU buffer **before**
    /// the render pass begins, using dynamic offsets to index each object's
    /// data during drawing.
    ///
    /// Each tuple may carry an optional material bind group.  When `Some`, the
    /// per-entity material is used; otherwise the default white material is
    /// applied.
    ///
    /// Each tuple may carry an optional texture index.  When `Some`, the
    /// texture at that index is used; otherwise the default texture is applied.
    pub fn render_3d_pass(
        &mut self,
        camera: &Camera,
        objects: &[(&Mesh, glam::Mat4, Option<&wgpu::BindGroup>, Option<u32>)],
        view: &wgpu::TextureView,
        encoder: &mut wgpu::CommandEncoder,
    ) {
        let align = self.uniform_alignment as usize;
        let uniform_size = std::mem::size_of::<CameraUniform>();
        let aligned_size = uniform_size.div_ceil(align) * align;

        if !objects.is_empty() {
            let total = aligned_size * objects.len();
            let mut data = vec![0u8; total];
            for (i, (_, model, _, _)) in objects.iter().enumerate() {
                let mut uniform = CameraUniform::new();
                uniform.update(camera, *model);
                let bytes = bytemuck::bytes_of(&uniform);
                let offset = i * aligned_size;
                data[offset..offset + uniform_size].copy_from_slice(bytes);
            }
            self.queue.write_buffer(&self.camera_buffer, 0, &data);
        }

        {
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("3D Render Pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.05,
                            g: 0.05,
                            b: 0.08,
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &self.depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Store,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
            });

            pass.set_pipeline(&self.render_pipeline);

            pass.set_bind_group(2, &self.lighting_bind_group, &[]);

            for (i, (mesh, _, mat_bg, tex_index)) in objects.iter().enumerate() {
                let dyn_offset = (i * aligned_size) as u32;
                pass.set_bind_group(0, &self.camera_bind_group, &[dyn_offset]);
                
                // Use the combined material + texture bind group
                let material_texture_bg = if mat_bg.is_some() || tex_index.is_some() {
                    // For now, we'll use the default combined bind group
                    // In a full implementation, we'd create combined bind groups for each material/texture pair
                    &self.default_material_texture_bind_group
                } else {
                    &self.default_material_texture_bind_group
                };
                pass.set_bind_group(1, material_texture_bg, &[]);
                
                pass.set_vertex_buffer(0, mesh.vertex_buffer.slice(..));
                pass.set_index_buffer(mesh.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
                pass.draw_indexed(0..mesh.index_count, 0, 0..1);
            }
        }
    }

    /// Perform the 3D clear + draw pass with mesh/material batching.
    ///
    /// Groups objects by (mesh, material) to minimize state changes.
    ///
    /// Each tuple may carry an optional material bind group.  When `Some`, the
    /// per-entity material is used; otherwise the default white material is
    /// applied.
    pub fn render_3d_pass_batched(
        &mut self,
        camera: &Camera,
        objects: &[(&Mesh, glam::Mat4, Option<&wgpu::BindGroup>, Option<u32>)],
        view: &wgpu::TextureView,
        encoder: &mut wgpu::CommandEncoder,
    ) {
        use std::collections::HashMap;

        let align = self.uniform_alignment as usize;
        let uniform_size = std::mem::size_of::<CameraUniform>();
        let aligned_size = uniform_size.div_ceil(align) * align;

        if !objects.is_empty() {
            let total = aligned_size * objects.len();
            let mut data = vec![0u8; total];
            for (i, (_, model, _, _)) in objects.iter().enumerate() {
                let mut uniform = CameraUniform::new();
                uniform.update(camera, *model);
                let bytes = bytemuck::bytes_of(&uniform);
                let offset = i * aligned_size;
                data[offset..offset + uniform_size].copy_from_slice(bytes);
            }
            self.queue.write_buffer(&self.camera_buffer, 0, &data);
        }

        // ── GPU-driven indirect rendering path ──
        if self.render_config.gpu_driven_culling {
            if let (Some(cull_pass), Some(mgr)) =
                (self.gpu_cull_pass.as_ref(), self.indirect_draw_manager.as_mut())
            {
                mgr.clear();
                for (mesh, model, _, _) in objects.iter() {
                    let (scale, _, translation) = model.to_scale_rotation_translation();
                    let half = scale.abs();
                    mgr.push(MeshDrawCommand {
                        index_count: mesh.index_count,
                        first_index: 0,
                        base_vertex: 0,
                        aabb_min: translation - half,
                        aabb_max: translation + half,
                        material_index: 0,
                    });
                }
                let vp = camera.view_projection();
                mgr.upload_aabbs(&self.queue, cull_pass);
                mgr.upload_uniforms(
                    &self.queue,
                    cull_pass,
                    &vp,
                    self.config.width as f32,
                    self.config.height as f32,
                );
                mgr.prepare_indirect_buffer(&self.queue, cull_pass);
                let bg = cull_pass.create_bind_group(&self.device);
                cull_pass.dispatch(encoder, &bg, mgr.count());

                {
                    let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                        label: Some("3D Render Pass (GPU Culled)"),
                        color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                            view,
                            resolve_target: None,
                            ops: wgpu::Operations {
                                load: wgpu::LoadOp::Clear(wgpu::Color {
                                    r: 0.05, g: 0.05, b: 0.08, a: 1.0,
                                }),
                                store: wgpu::StoreOp::Store,
                            },
                        })],
                        depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                            view: &self.depth_view,
                            depth_ops: Some(wgpu::Operations {
                                load: wgpu::LoadOp::Clear(1.0),
                                store: wgpu::StoreOp::Store,
                            }),
                            stencil_ops: None,
                        }),
                        timestamp_writes: None,
                        occlusion_query_set: None,
                    });

                    pass.set_pipeline(&self.render_pipeline);
            pass.set_bind_group(2, &self.lighting_bind_group, &[]);

                    let stride = std::mem::size_of::<DrawIndexedIndirectArgs>() as u64;
for (i, (mesh, _, _mat_bg, _tex_index)) in objects.iter().enumerate() {
                        let dyn_offset = (i * aligned_size) as u32;
                        pass.set_bind_group(0, &self.camera_bind_group, &[dyn_offset]);
                        
// Use the combined material + texture bind group
let material_texture_bg = &self.default_material_texture_bind_group;
                        pass.set_bind_group(1, material_texture_bg, &[]);
                        
                        pass.set_vertex_buffer(0, mesh.vertex_buffer.slice(..));
                        pass.set_index_buffer(mesh.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
                        pass.draw_indexed_indirect(&cull_pass.indirect_buffer, i as u64 * stride);
                    }
                }
            }
            return;
        }

type BatchKey = (usize, usize, usize);
#[allow(dead_code)]
struct Batch {
mesh: &'static Mesh,
indices: Vec<usize>,
material: Option<&'static wgpu::BindGroup>,
texture: &'static wgpu::BindGroup,
}

        let mut batches: HashMap<BatchKey, Batch> = HashMap::new();

        for (i, (mesh, _, mat_bg, tex_index)) in objects.iter().enumerate() {
            let mesh_key = *mesh as *const Mesh as usize;
            let mat_key = mat_bg.map(|bg| bg as *const wgpu::BindGroup as usize)
                .unwrap_or(usize::MAX);
            let tex_key = tex_index.unwrap_or(0) as usize;

            let entry = batches.entry((mesh_key, mat_key, tex_key)).or_insert_with(|| {
                let texture_bg = self.get_texture_bind_group(tex_index.unwrap_or(0));
                Batch {
                    mesh: unsafe { &*(*mesh as *const Mesh) },
                    indices: Vec::new(),
                    material: mat_bg.map(|bg| unsafe { &*(bg as *const wgpu::BindGroup) }),
                    texture: unsafe { &*(texture_bg as *const wgpu::BindGroup) },
                }
            });
            entry.indices.push(i);
        }

        {
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("3D Render Pass (Batched)"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.05,
                            g: 0.05,
                            b: 0.08,
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &self.depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Store,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
            });

            pass.set_pipeline(&self.render_pipeline);

            pass.set_bind_group(2, &self.lighting_bind_group, &[]);

        for batch in batches.values() {
            // Use the batch's material texture bind group
            pass.set_bind_group(1, batch.texture, &[]);
            pass.set_vertex_buffer(0, batch.mesh.vertex_buffer.slice(..));
            pass.set_index_buffer(batch.mesh.index_buffer.slice(..), wgpu::IndexFormat::Uint32);

                for &idx in &batch.indices {
                    let dyn_offset = (idx * aligned_size) as u32;
                    pass.set_bind_group(0, &self.camera_bind_group, &[dyn_offset]);
                    pass.draw_indexed(0..batch.mesh.index_count, 0, 0..1);
                }
            }
        }
    }

    /// Submit the encoder and present the frame.
    pub fn finish_frame(
        &self,
        encoder: wgpu::CommandEncoder,
        output: wgpu::SurfaceTexture,
    ) {
        self.queue.submit(std::iter::once(encoder.finish()));
        output.present();
    }

    // ── Legacy one-shot rendering ────────────────────────────────

    /// Render a single frame: clear the screen and draw all provided meshes.
    pub fn render(&self, meshes: &[&Mesh]) -> Result<(), wgpu::SurfaceError> {
        let output = self.surface.get_current_texture()?;
        let view = output
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("Render Encoder"),
            });

        {
            let mut render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("Main Render Pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.05,
                            g: 0.05,
                            b: 0.08,
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &self.depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Store,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
            });

            render_pass.set_pipeline(&self.render_pipeline);
            render_pass.set_bind_group(0, &self.camera_bind_group, &[0]);
            render_pass.set_bind_group(1, &self.default_material_texture_bind_group, &[]);
            render_pass.set_bind_group(2, &self.lighting_bind_group, &[]);

            for mesh in meshes {
                render_pass.set_vertex_buffer(0, mesh.vertex_buffer.slice(..));
                render_pass
                    .set_index_buffer(mesh.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
                render_pass.draw_indexed(0..mesh.index_count, 0, 0..1);
            }
        }

        self.queue.submit(std::iter::once(encoder.finish()));
        output.present();

        Ok(())
    }

    /// Render a frame with multiple objects, each with its own model matrix.
    ///
    /// Pre-writes all per-object camera uniforms to the GPU buffer before the
    /// render pass, then uses dynamic offsets to select each object's data.
    ///
    /// Each tuple may carry an optional material bind group.  When `Some`, the
    /// per-entity material is used; otherwise the default white material is
    /// applied.
    ///
    /// Each tuple may carry an optional texture index.  When `Some`, the
    /// texture at that index is used; otherwise the default texture is used.
    pub fn render_objects(
        &mut self,
        camera: &Camera,
        objects: &[(&Mesh, glam::Mat4, Option<&wgpu::BindGroup>, Option<u32>)],
    ) -> Result<(), wgpu::SurfaceError> {
        self.render_objects_internal(camera, objects, false)
    }

    /// Render a frame with GPU instancing for objects sharing the same mesh.
    ///
    /// Groups objects by (mesh, material) to minimize draw calls.  For each group,
    /// all instances are drawn in a single instanced draw call.
    ///
    /// Each tuple may carry an optional material bind group.  When `Some`, the
    /// per-entity material is used; otherwise the default white material is used.
    ///
    /// Each tuple may carry an optional texture index.  When `Some`, the
    /// texture at that index is used; otherwise the default texture is used.
    pub fn render_objects_instanced(
        &mut self,
        camera: &Camera,
        objects: &[(&Mesh, glam::Mat4, Option<&wgpu::BindGroup>, Option<u32>)],
    ) -> Result<(), wgpu::SurfaceError> {
        let output = self.surface.get_current_texture()?;
        let view = output
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("Render Encoder"),
            });

        let align = self.uniform_alignment as usize;
        let uniform_size = std::mem::size_of::<CameraUniform>();
        let aligned_size = uniform_size.div_ceil(align) * align;

        if !objects.is_empty() {
            let total = aligned_size * objects.len();
            let mut data = vec![0u8; total];
            let mut uniform = CameraUniform::new();
            uniform.view_proj = camera.view_projection().to_cols_array_2d();
            uniform.normal_matrix = glam::Mat4::IDENTITY.to_cols_array_2d();
            let bytes = bytemuck::bytes_of(&uniform);
            for i in 0..objects.len() {
                let offset = i * aligned_size;
                data[offset..offset + uniform_size].copy_from_slice(bytes);
            }
            self.queue.write_buffer(&self.camera_buffer, 0, &data);
        }

        use std::collections::HashMap;

        type BatchKey = (usize, usize, usize);
        struct Batch {
            mesh: *const Mesh,
            materials: Vec<glam::Mat4>,
            material: Option<*const wgpu::BindGroup>,
            texture: *const wgpu::BindGroup,
        }

        let mut batches: HashMap<BatchKey, Batch> = HashMap::new();

        for (mesh, model, mat_bg, tex_index) in objects.iter() {
            let mesh_key = *mesh as *const Mesh as usize;
            let mat_key = mat_bg.map(|bg| bg as *const wgpu::BindGroup as usize)
                .unwrap_or(usize::MAX);
            let tex_key = tex_index.unwrap_or(0) as usize;

            let entry = batches.entry((mesh_key, mat_key, tex_key)).or_insert_with(|| {
                let texture_bg: *const wgpu::BindGroup = self.get_texture_bind_group(tex_index.unwrap_or(0));
                let mat_ptr: Option<*const wgpu::BindGroup> = mat_bg.map(|bg| bg as *const wgpu::BindGroup);
                Batch {
                    mesh: *mesh as *const Mesh,
                    materials: Vec::new(),
                    material: mat_ptr,
                    texture: texture_bg,
                }
            });
            entry.materials.push(*model);
        }

        {
            let mut render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("Main Render Pass (Instanced)"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.05,
                            g: 0.05,
                            b: 0.08,
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &self.depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Store,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
            });

            render_pass.set_pipeline(&self.render_pipeline);
            render_pass.set_bind_group(2, &self.lighting_bind_group, &[]);
            render_pass.set_bind_group(4, &self.instance_bind_group, &[]);

            for batch in batches.values() {
                let material_bg = batch.material.unwrap_or(&self.default_material.bind_group as *const wgpu::BindGroup);
                render_pass.set_bind_group(1, unsafe { &*material_bg }, &[]);
                render_pass.set_bind_group(3, unsafe { &*batch.texture }, &[]);
                render_pass.set_vertex_buffer(0, unsafe { &(*batch.mesh).vertex_buffer }.slice(..));
                render_pass.set_index_buffer(unsafe { &(*batch.mesh).index_buffer }.slice(..), wgpu::IndexFormat::Uint32);

                if !batch.materials.is_empty() {
                    let matrix_bytes: Vec<u8> = batch.materials
                        .iter()
                        .flat_map(|m| bytemuck::bytes_of(m).iter().copied())
                        .collect();
                    self.queue.write_buffer(&self.instance_buffer, 0, &matrix_bytes);

                    render_pass.draw_indexed(
                        0..unsafe { (*batch.mesh).index_count },
                        0,
                        0..batch.materials.len() as u32,
                    );
                }
            }
        }

        self.queue.submit(std::iter::once(encoder.finish()));
        output.present();

        Ok(())
    }

    fn render_objects_internal(
        &mut self,
        camera: &Camera,
        objects: &[(&Mesh, glam::Mat4, Option<&wgpu::BindGroup>, Option<u32>)],
        use_instancing: bool,
    ) -> Result<(), wgpu::SurfaceError> {
        let output = self.surface.get_current_texture()?;
        let view = output
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("Render Encoder"),
            });

        let align = self.uniform_alignment as usize;
        let uniform_size = std::mem::size_of::<CameraUniform>();
        let aligned_size = uniform_size.div_ceil(align) * align;

        if !objects.is_empty() {
            let total = aligned_size * objects.len();
            let mut data = vec![0u8; total];
            for (i, (_, model, _, _)) in objects.iter().enumerate() {
                let mut uniform = CameraUniform::new();
                uniform.update(camera, *model);
                let bytes = bytemuck::bytes_of(&uniform);
                let offset = i * aligned_size;
                data[offset..offset + uniform_size].copy_from_slice(bytes);
            }
            self.queue.write_buffer(&self.camera_buffer, 0, &data);
        }

        {
            let mut render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("Main Render Pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.05,
                            g: 0.05,
                            b: 0.08,
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &self.depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Store,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
            });

            render_pass.set_pipeline(&self.render_pipeline);

            if use_instancing {
                use std::collections::HashMap;

                type BatchKey = (usize, usize, usize);
                struct Batch {
                    mesh: &'static Mesh,
                    indices: Vec<usize>,
                    material: Option<&'static wgpu::BindGroup>,
                    texture: &'static wgpu::BindGroup,
                }

                let mut batches: HashMap<BatchKey, Batch> = HashMap::new();

                for (i, (mesh, _, mat_bg, tex_index)) in objects.iter().enumerate() {
                    let mesh_key = *mesh as *const Mesh as usize;
                    let mat_key = mat_bg.map(|bg| bg as *const wgpu::BindGroup as usize)
                        .unwrap_or(usize::MAX);
                    let tex_key = tex_index.unwrap_or(0) as usize;

                    let entry = batches.entry((mesh_key, mat_key, tex_key)).or_insert_with(|| {
                        let texture_bg = self.get_texture_bind_group(tex_index.unwrap_or(0));
                        Batch {
                            mesh: unsafe { &*(*mesh as *const Mesh) },
                            indices: Vec::new(),
                            material: mat_bg.map(|bg| unsafe { &*(bg as *const wgpu::BindGroup) }),
                            texture: unsafe { &*(texture_bg as *const wgpu::BindGroup) },
                        }
                    });
                    entry.indices.push(i);
                }

                for batch in batches.values() {
                    let material_bg = batch.material.unwrap_or(&self.default_material.bind_group);
                    render_pass.set_bind_group(1, material_bg, &[]);
                    render_pass.set_bind_group(2, &self.lighting_bind_group, &[]);
                    render_pass.set_bind_group(3, batch.texture, &[]);
                    render_pass.set_vertex_buffer(0, batch.mesh.vertex_buffer.slice(..));
                    render_pass.set_index_buffer(batch.mesh.index_buffer.slice(..), wgpu::IndexFormat::Uint32);

                    for &idx in &batch.indices {
                        let dyn_offset = (idx * aligned_size) as u32;
                        render_pass.set_bind_group(0, &self.camera_bind_group, &[dyn_offset]);
                        render_pass.draw_indexed(0..batch.mesh.index_count, 0, 0..1);
                    }
                }
            } else {
                render_pass.set_bind_group(2, &self.lighting_bind_group, &[]);

                for (i, (mesh, _, mat_bg, tex_index)) in objects.iter().enumerate() {
                    let dyn_offset = (i * aligned_size) as u32;
                    render_pass.set_bind_group(0, &self.camera_bind_group, &[dyn_offset]);
                    let material_bg = mat_bg.unwrap_or(&self.default_material.bind_group);
                    render_pass.set_bind_group(1, material_bg, &[]);
                    let texture_bg = self.get_texture_bind_group(tex_index.unwrap_or(0));
                    render_pass.set_bind_group(3, texture_bg, &[]);
                    render_pass.set_vertex_buffer(0, mesh.vertex_buffer.slice(..));
                    render_pass.set_index_buffer(mesh.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
                    render_pass.draw_indexed(0..mesh.index_count, 0, 0..1);
                }
            }
        }

        self.queue.submit(std::iter::once(encoder.finish()));
        output.present();

        Ok(())
    }

    /// Create a [`Material`] from a [`MaterialOverride`] component.
    ///
    /// The returned material has its GPU buffer already uploaded and is ready
    /// to be passed as a bind group to
    /// [`render_3d_pass`](Self::render_3d_pass) /
    /// [`render_objects`](Self::render_objects).
    pub fn create_material_from_override(
        &self,
        name: &str,
        material_override: &MaterialOverride,
    ) -> Material {
        Material::from_override(
            &self.device,
            &self.queue,
            &self.material_texture_bind_group_layout,
            name,
            material_override,
        )
    }

    /// Create a depth texture and its view.
    fn create_depth_texture(
        device: &wgpu::Device,
        width: u32,
        height: u32,
        sample_count: u32,
    ) -> (wgpu::Texture, wgpu::TextureView) {
        let size = wgpu::Extent3d {
            width,
            height,
            depth_or_array_layers: 1,
        };
        let texture = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("Depth Texture"),
            size,
            mip_level_count: 1,
            sample_count,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Depth32Float,
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::TEXTURE_BINDING,
            view_formats: &[],
        });
        let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
        (texture, view)
    }

    /// Create a zero-initialised Rg16Float motion vector texture.
    fn create_motion_vector_texture(
        device: &wgpu::Device,
        width: u32,
        height: u32,
    ) -> (wgpu::Texture, wgpu::TextureView) {
        let texture = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("Motion Vector Texture"),
            size: wgpu::Extent3d {
                width,
                height,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rg16Float,
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::TEXTURE_BINDING,
            view_formats: &[],
        });
        let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
        (texture, view)
    }
}
